import '../styles/globals.css'
import LoadingBar from 'react-top-loading-bar'
import { useEffect, useState } from 'react'
import { useRouter,router } from 'next/router'
import Head from 'next/head'
import Script from 'next/script'

function MyApp({ Component, pageProps }) {
  const [progress, setProgress] = useState(0)


  useEffect(()=>{
    router.events.on('routeChangeStart', ()=>{
      setProgress(40)
    })
    router.events.on('routeChangeComplete', ()=>{
      setProgress(100)
    })
  })

  return <>
  <LoadingBar
      color='#f11946'
      waitingTime= {400}
      progress={progress}
      onLoaderFinished={() => setProgress(0)}
    />
  <Head>
    <title>Wordpress Blog</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"></link>
  </Head>
  
  <Script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" />
  <Component {...pageProps} />    
</>
}

export default MyApp
